/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vistas;

import java.awt.Color;
import java.awt.Toolkit;
import javax.swing.ImageIcon;
import misc.Funciones;

/**
 *
 * @author Mariel Mata <mlmtcrdn@gmail.com>
 */
public class Inicio extends javax.swing.JFrame {

    /**
     * Creates new form Inicio
     */
    public Inicio() {
        initComponents();
//        setIconImage(new ImageIcon(getClass().getResource("/Recursos/iconhdr.png")).getImage());
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("/Recursos/hdricon.png")));
        Funciones f = new Funciones();
        f.creaCarpeta();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        pCerrar = new javax.swing.JPanel();
        jlX = new javax.swing.JLabel();
        jpAgregar = new javax.swing.JPanel();
        jpTextoA = new javax.swing.JLabel();
        jlTitulo = new javax.swing.JLabel();
        jpVer = new javax.swing.JPanel();
        jlTextoV = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 208, 220));

        pCerrar.setBackground(new java.awt.Color(255, 208, 220));
        pCerrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pCerrarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                pCerrarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                pCerrarMouseExited(evt);
            }
        });

        jlX.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jlX.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlX.setText("X");

        javax.swing.GroupLayout pCerrarLayout = new javax.swing.GroupLayout(pCerrar);
        pCerrar.setLayout(pCerrarLayout);
        pCerrarLayout.setHorizontalGroup(
            pCerrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jlX, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE)
        );
        pCerrarLayout.setVerticalGroup(
            pCerrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jlX, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE)
        );

        jpAgregar.setBackground(new java.awt.Color(221, 108, 142));
        jpAgregar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jpAgregarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jpAgregarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jpAgregarMouseExited(evt);
            }
        });

        jpTextoA.setFont(new java.awt.Font("Georgia", 0, 14)); // NOI18N
        jpTextoA.setForeground(new java.awt.Color(255, 255, 255));
        jpTextoA.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jpTextoA.setText("Agregar recetas");

        javax.swing.GroupLayout jpAgregarLayout = new javax.swing.GroupLayout(jpAgregar);
        jpAgregar.setLayout(jpAgregarLayout);
        jpAgregarLayout.setHorizontalGroup(
            jpAgregarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpAgregarLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jpTextoA, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jpAgregarLayout.setVerticalGroup(
            jpAgregarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpAgregarLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jpTextoA)
                .addContainerGap())
        );

        jlTitulo.setFont(new java.awt.Font("Calisto MT", 0, 24)); // NOI18N
        jlTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlTitulo.setText("Hora del postre");

        jpVer.setBackground(new java.awt.Color(221, 108, 142));
        jpVer.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jpVerMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jpVerMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jpVerMouseExited(evt);
            }
        });

        jlTextoV.setFont(new java.awt.Font("Georgia", 0, 14)); // NOI18N
        jlTextoV.setForeground(new java.awt.Color(255, 255, 255));
        jlTextoV.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlTextoV.setText("Ver recetas");

        javax.swing.GroupLayout jpVerLayout = new javax.swing.GroupLayout(jpVer);
        jpVer.setLayout(jpVerLayout);
        jpVerLayout.setHorizontalGroup(
            jpVerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpVerLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jlTextoV, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jpVerLayout.setVerticalGroup(
            jpVerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpVerLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jlTextoV)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jSeparator1.setForeground(new java.awt.Color(51, 51, 51));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(pCerrar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator1)
                    .addComponent(jlTitulo, javax.swing.GroupLayout.DEFAULT_SIZE, 195, Short.MAX_VALUE)
                    .addComponent(jpAgregar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jpVer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(pCerrar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jlTitulo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jpAgregar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jpVer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(28, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jpAgregarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jpAgregarMouseClicked
        AgregarReceta ar = new AgregarReceta(this, true);
        ar.setVisible(true);
    }//GEN-LAST:event_jpAgregarMouseClicked

    private void pCerrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pCerrarMouseClicked
        System.exit(0);
    }//GEN-LAST:event_pCerrarMouseClicked

    private void jpVerMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jpVerMouseClicked
        VerRecetas vr = new VerRecetas(this, true);
        vr.setVisible(true);
    }//GEN-LAST:event_jpVerMouseClicked

    private void pCerrarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pCerrarMouseEntered
        pCerrar.setBackground(Color.red);
        jlX.setForeground(Color.white);
    }//GEN-LAST:event_pCerrarMouseEntered

    private void pCerrarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pCerrarMouseExited
        pCerrar.setBackground(Color.decode("#FFD0DC"));
        jlX.setForeground(Color.black);
    }//GEN-LAST:event_pCerrarMouseExited

    private void jpAgregarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jpAgregarMouseEntered
        jpAgregar.setBackground(Color.decode("#A6576E"));
    }//GEN-LAST:event_jpAgregarMouseEntered

    private void jpAgregarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jpAgregarMouseExited
        jpAgregar.setBackground(Color.decode("#DD6C8E"));
    }//GEN-LAST:event_jpAgregarMouseExited

    private void jpVerMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jpVerMouseEntered
        jpVer.setBackground(Color.decode("#A6576E"));
    }//GEN-LAST:event_jpVerMouseEntered

    private void jpVerMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jpVerMouseExited
        jpVer.setBackground(Color.decode("#DD6C8E"));
    }//GEN-LAST:event_jpVerMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Inicio().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel jlTextoV;
    private javax.swing.JLabel jlTitulo;
    private javax.swing.JLabel jlX;
    private javax.swing.JPanel jpAgregar;
    private javax.swing.JLabel jpTextoA;
    private javax.swing.JPanel jpVer;
    private javax.swing.JPanel pCerrar;
    // End of variables declaration//GEN-END:variables
}
