/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vistas;

import horadelpostre.HoraDelPostre;
import java.awt.Image;
import java.io.File;
import java.io.FileWriter;
import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Paths;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import misc.RecetaClase;
import vistas.Inicio;

/**
 *
 * @author Mariel Mata <mlmtcrdn@gmail.com>
 */
public class VistaDeReceta extends javax.swing.JFrame {

    RecetaClase recetaActiva = null;
    String carpetaPrincipal = "D:\\Documents\\Recetas_Hora_del_postre";

    /**
     * Creates new form VistaDeReceta
     */
    public VistaDeReceta() {
        initComponents();
        setIconImage(new ImageIcon(getClass().getResource("/iconpastel.png")).getImage());
        String tituloReceta = Inicio.jlRecetas.getSelectedValue();
        RecetaAVer(tituloReceta);
        this.setTitle(tituloReceta);
        jtfNombreReceta.setText(recetaActiva.getNombre());
        jtaIngredientes.setText(recetaActiva.getIngredientes());
        jtaUtensilios.setText(recetaActiva.getUtensilios());
        jtaProcedimiento.setText(recetaActiva.getProcedimiento());
        ImageIcon imagen = new ImageIcon(recetaActiva.getImagen());
        Icon icono = new ImageIcon(imagen.getImage().getScaledInstance(
                jlImagen.getWidth(), 
                jlImagen.getHeight(), 
                Image.SCALE_DEFAULT));
        jlImagen.setIcon(icono);
        jbEditarImagenes.setVisible(false);
        jbGuardar.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jtfNombreReceta = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtaIngredientes = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        jtaUtensilios = new javax.swing.JTextArea();
        jScrollPane3 = new javax.swing.JScrollPane();
        jtaProcedimiento = new javax.swing.JTextArea();
        jbGuardar = new javax.swing.JButton();
        jbEditar = new javax.swing.JButton();
        jbEditarImagenes = new javax.swing.JButton();
        jlImagen = new javax.swing.JLabel();

        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(249, 247, 220));

        jtfNombreReceta.setEditable(false);
        jtfNombreReceta.setBackground(new java.awt.Color(248, 232, 180));
        jtfNombreReceta.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jtfNombreReceta.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jtfNombreReceta.setBorder(null);

        jtaIngredientes.setEditable(false);
        jtaIngredientes.setBackground(new java.awt.Color(248, 232, 180));
        jtaIngredientes.setColumns(20);
        jtaIngredientes.setRows(5);
        jtaIngredientes.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Ingredientes", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 12))); // NOI18N
        jScrollPane1.setViewportView(jtaIngredientes);

        jtaUtensilios.setEditable(false);
        jtaUtensilios.setBackground(new java.awt.Color(248, 232, 180));
        jtaUtensilios.setColumns(20);
        jtaUtensilios.setRows(5);
        jtaUtensilios.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Utensilios", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 12))); // NOI18N
        jScrollPane2.setViewportView(jtaUtensilios);

        jtaProcedimiento.setEditable(false);
        jtaProcedimiento.setBackground(new java.awt.Color(248, 232, 180));
        jtaProcedimiento.setColumns(20);
        jtaProcedimiento.setRows(5);
        jtaProcedimiento.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Procedimiento", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 12))); // NOI18N
        jScrollPane3.setViewportView(jtaProcedimiento);

        jbGuardar.setBackground(new java.awt.Color(208, 126, 46));
        jbGuardar.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jbGuardar.setForeground(new java.awt.Color(118, 60, 0));
        jbGuardar.setText("Guardar Cambios");
        jbGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbGuardarActionPerformed(evt);
            }
        });

        jbEditar.setBackground(new java.awt.Color(208, 126, 46));
        jbEditar.setForeground(new java.awt.Color(118, 60, 0));
        jbEditar.setText("✏");
        jbEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbEditarActionPerformed(evt);
            }
        });

        jbEditarImagenes.setBackground(new java.awt.Color(208, 126, 46));
        jbEditarImagenes.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jbEditarImagenes.setForeground(new java.awt.Color(118, 60, 0));
        jbEditarImagenes.setText("Editar Imagen");
        jbEditarImagenes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbEditarImagenesActionPerformed(evt);
            }
        });

        jlImagen.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(74, 74, 74)
                        .addComponent(jbEditar)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jlImagen, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(34, 34, 34)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jbGuardar)
                                    .addComponent(jbEditarImagenes, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jtfNombreReceta, javax.swing.GroupLayout.PREFERRED_SIZE, 365, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 263, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 265, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 373, Short.MAX_VALUE)))))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jlImagen, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jbEditarImagenes)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jbGuardar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jbEditar)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jtfNombreReceta, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 203, Short.MAX_VALUE)
                        .addGap(6, 6, 6)))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jbEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbEditarActionPerformed
        // TODO add your handling code here:
        jbEditarImagenes.setVisible(true);
        jbGuardar.setVisible(true);
        jtaIngredientes.setEditable(true);
        jtaProcedimiento.setEditable(true);
        jtaUtensilios.setEditable(true);
    }//GEN-LAST:event_jbEditarActionPerformed

    private void jbGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbGuardarActionPerformed
        // TODO add your handling code here:
        EditarReceta(jtfNombreReceta.getText());
        JOptionPane.showMessageDialog(null, "La receta " + recetaActiva.getNombre() + " se ha modificado");
    }//GEN-LAST:event_jbGuardarActionPerformed

    private void jbEditarImagenesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbEditarImagenesActionPerformed
        
    }//GEN-LAST:event_jbEditarImagenesActionPerformed

    public void EditarReceta(String receta) {
        String ruta = carpetaPrincipal + "\\" + receta;
        try {
            FileWriter recipeI = new FileWriter(ruta + "\\Ingredientes.txt", false);
            FileWriter recipeU = new FileWriter(ruta + "\\Utensilios.txt", false);
            FileWriter recipeP = new FileWriter(ruta + "\\Procedimiento.txt", false);
            recipeI.write(jtaIngredientes.getText());
            recipeI.close();
            recipeU.write(jtaUtensilios.getText());
            recipeU.close();
            recipeP.write(jtaProcedimiento.getText());
            recipeP.close();
        } catch (IOException ex) {
            Logger.getLogger(HoraDelPostre.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    public void RecetaAVer(String recetaSelect) {
        File fileIng = null;
        File fileUten = null;
        File fileProc = null;

        try {
            String rutaCarpeta = carpetaPrincipal + "\\" + recetaSelect;
            String rutaIng = rutaCarpeta + "\\Ingredientes.txt";
            String rutaUten = rutaCarpeta + "\\Utensilios.txt";
            String rutaProc = rutaCarpeta + "\\Procedimiento.txt";
            String rutaImagenJPG = rutaCarpeta + "\\imagen.jpg";
            String rutaImagenPNG = rutaCarpeta + "\\imagen.png";
            String rutaImagenJPEG = rutaCarpeta + "\\imagen.jpeg";
            fileIng = new File(rutaIng);
            fileUten = new File(rutaUten);
            fileProc = new File(rutaProc);
            File imgPNG = new File(rutaImagenPNG);
            File imgJPG = new File(rutaImagenJPG);
            File imgJPEG = new File(rutaImagenJPEG);

            String nombRec = recetaSelect;
            String ingRec = new String(Files.readAllBytes(Paths.get(rutaIng)));
            String utenRec = new String(Files.readAllBytes(Paths.get(rutaUten)));
            String procRec = new String(Files.readAllBytes(Paths.get(rutaProc)));

            if (imgJPG.exists()) {
                recetaActiva = new RecetaClase(nombRec, ingRec, utenRec, procRec, rutaImagenJPG);
            } else if (imgPNG.exists()) {
                recetaActiva = new RecetaClase(nombRec, ingRec, utenRec, procRec, rutaImagenPNG);
            } else {
                recetaActiva = new RecetaClase(nombRec, ingRec, utenRec, procRec, rutaImagenJPEG);
            }

        } catch (IOException ex) {
            Logger.getLogger(Inicio.class.getName()).log(Level.SEVERE, null, ex);
        }

    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VistaDeReceta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VistaDeReceta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VistaDeReceta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VistaDeReceta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VistaDeReceta().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JButton jbEditar;
    private javax.swing.JButton jbEditarImagenes;
    private javax.swing.JButton jbGuardar;
    private javax.swing.JLabel jlImagen;
    private javax.swing.JTextArea jtaIngredientes;
    private javax.swing.JTextArea jtaProcedimiento;
    private javax.swing.JTextArea jtaUtensilios;
    private javax.swing.JTextField jtfNombreReceta;
    // End of variables declaration//GEN-END:variables
}
